# Generated by Django 6.0.1 on 2026-01-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_scan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='freescan',
            name='target_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
