# Generated by Django 6.0 on 2026-01-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_freescan_target_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('Quick', 'Quick'), ('Deep', 'Deep')], default='Quick', max_length=10),
        ),
    ]
