# Generated by Django 6.0 on 2026-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_scan_scan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='scan_type',
        ),
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
