# Generated by Django 6.0 on 2026-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_remove_scan_scan_type_scan_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('Quick', 'Quick'), ('Deep', 'Deep')], default='Quick', max_length=10),
        ),
    ]
